# If you're using permissions, the default configuration nodes are 'simplehealth.users' and 'simplehealth.admins'
# You can specify as many groups in this file as you want, and include them in permissions with 'simplehealth.[groupname]'
# If you're not using permissions, the default group names of 'users' and 'admins' can't be changed (it will throw errors if you change them)
plugin:
  # Any worlds specified here will have regeneration applied to them. Worlds not specified will remain unaffected.
  worlds:
    - 'world'
    - 'world_nether'
  # If your server uses peaceful mode, and you don't want users to regen super fast
  # Any worlds specified here will have no natural health regeneration
  # This will negate the fast regen effect of peaceful servers
  natural_regen:
    - 'world'
    - 'world_nether'
  # Any worlds specified here will have blocked PVP combat.
  pvp:
    - 'world_nether'
  permissions: false
  default_locale: 'en_US'
  locales: [en_US]

groups:
  users:
    regen:
      # rate in seconds that the user regenerates health (0 for disabled)
      rate: 30
      # amount in health (2 health = 1 heart) per regeneration tick
      amount: 1
    disabled_commands:
      # '*' will match all commands
      - 'warp'
    events:
      # these values will influence the amount of health upon certain events
      # the values may be modified freely, but don't exceed 20 or enter 0
      # currently, only _respawn works.
      # TODO:
      #   _damage: floor damage inflicted to the amount specified in this config
      # _damage: 0 (god mode?)
      _respawn: 1
    items:
      # any value specified after a material name will cause the player to gain health after using it
      # you could even specify "stone" or "obsidian" to heal players
      # values specified here will override default game values
      # If you specify a block (stone, obsidian, etc), the block will be consumed until the player's health is full
      # at which point the block will be placeable normally again
      # negative values can be given
      pork: 3
      grilled_pork: 6
  admins:
    regen:
      rate: 10
      amount: 1
    disabled_commands:
    events:
      _respawn: 20
    items:
      pork: 10
      grilled_pork: 20